name: datapro
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py314h2b7f5b3_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - et_xmlfile=1.0.1=py_1001
  - expat=2.7.3=h9214b88_0
  - intel-openmp=2025.0.0=haa95532_1164
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libmpdec=4.0.0=h827c3e9_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py314h0b37514_0
  - mkl_fft=2.1.1=py314h281c9fe_0
  - mkl_random=1.3.0=py314hdbada53_0
  - numexpr=2.14.1=py314h2592778_0
  - numpy=2.3.5=py314h0be4137_0
  - numpy-base=2.3.5=py314h96ad93d_0
  - openpyxl=3.1.5=py314h827c3e9_1
  - openssl=3.0.18=h543e019_0
  - pandas=2.3.3=py314hdbada53_1
  - pip=25.3=pyh0d26453_0
  - python=3.14.0=h3bc0a5a_101_cp314
  - python-dateutil=2.9.0post0=py314haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=py314haa95532_0
  - six=1.17.0=py314haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - docx==0.2.4
      - lxml==6.0.2
      - pillow==12.0.0
      - python-docx==1.2.0
      - typing-extensions==4.15.0
prefix: D:\Software\Miniconda\envs\datapro
